language: php

php:
  - 5.6
  - 7

install: composer install

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/

script:
  - ./vendor/bin/phpunit tests
  - ./vendor/bin/php-cs-fixer fix src --dry-run
  - ./vendor/bin/php-cs-fixer fix tests --dry-run
  - ./vendor/bin/php-cs-fixer fix examples --dry-run

branches:
  only:
    - master

notifications:
  email:
    on_success: never
