language: php

php:
  - 7.2

install: composer install

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/

script:
  - ./vendor/bin/phpunit tests
  - ./vendor/bin/php-cs-fixer fix src --dry-run -v --rules=@PSR2
  - ./vendor/bin/php-cs-fixer fix tests --dry-run -v --rules=@PSR2
  - ./vendor/bin/php-cs-fixer fix examples --dry-run -v --rules=@PSR2

branches:
  only:
    - master

notifications:
  email:
    on_success: never
